version: '3.8'

services:
  todo:
    image: 'todo:latest'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_TESTS=true
    container_name: todo
    depends_on:
      - db
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - DB_NAME
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"