services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'todo-api:latest'
    environment:
      -DB_HOST=database
      -DB_PORT=5432
      -DB_NAME=tododb
      -DB_USERNAME=${DB_USERNAME}
      -DB_PASSWORD=${DB_PASSWORD}
    ports:
      -"8080:8080"

database:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432'