server:
  port: 8090

spring:
  profiles:
    active: qa

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: todo
  datasource:
    username: ${db_user}
    password: ${db_psswd}
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '2000'
    url: jdbc:postgresql://localhost:5432/postgres-dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---

spring:
  config:
    activate:
      on-profile: qa
  application:
    name: todo
  datasource:
    username: ${db_user}
    password: ${db_psswd}
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '2000'
    url: jdbc:postgresql://localhost:5432/postgres-qa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: todo
  datasource:
    username: ${db_user}
    password: ${db_psswd}
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '2000'
    url: jdbc:postgresql://localhost:5432/postgres-prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update